apiVersion: v1
kind: Service
metadata:
  name: battleship
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: battleship
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
